clear all
A = 1;
omega = pi / 16;
theta = 0;
N = 150;
n = 0:N - 1;
s = A * cos(omega * n + theta);
rand_z = rand(size(s));
z = (rand_z - 0.5) * 0.6;
x = s + z;
y1 = Move_Ave(3, x);
y2 = Move_Ave(5, x);
y3 = Move_Ave(7, x);
y4 = Move_Ave(9, x);
y5 = Move_Ave(11, x);
figure(1);
subplot(2, 1, 1);
stem(n, x, 'filled', 'markersize', 3);
xlabel('$n$', 'Interpreter', 'LaTex');
ylabel('$x[n]$', 'Interpreter', 'LaTex');
title('含噪声的正弦序列');
subplot(2, 1, 2);
stem(n, y1, 'filled', 'markersize', 3);
xlabel('$n$', 'Interpreter', 'LaTex');
ylabel('$y_1[n]$', 'Interpreter', 'LaTex');
title('3点滑动平均滤波');

figure(2);
subplot(2, 1, 1);
stem(n, y2, 'filled', 'markersize', 3);
xlabel('$n$', 'Interpreter', 'LaTex');
ylabel('$y_2[n]$', 'Interpreter', 'LaTex');
title('5点滑动平均滤波');
axis([-2 151 -1.5 1.5]);
subplot(2, 1, 2);
stem(n, y3, 'filled', 'markersize', 3);
xlabel('$n$', 'Interpreter', 'LaTex');
ylabel('$y_3[n]$', 'Interpreter', 'LaTex');
title('7点滑动平均滤波');

figure(3);
subplot(2, 1, 1);
stem(n, y4, 'filled', 'markersize', 3);
xlabel('$n$', 'Interpreter', 'LaTex');
ylabel('$y_4[n]$', 'Interpreter', 'LaTex');
title('9点滑动平均滤波');
subplot(2, 1, 2);
stem(n, y5, 'filled', 'markersize', 3);
xlabel('$n$', 'Interpreter', 'LaTex');
ylabel('$y_5[n]$', 'Interpreter', 'LaTex');
title('11点滑动平均滤波');
